// HTTP/1.x message heads and an incremental parser.
//
// The parser fully decodes the head (request/status line and headers) but
// treats the body as opaque bytes whose only job is to find where the message
// ends: Content-Length, chunked encoding (sizes, extensions and trailers) or
// read-until-close. The proxy forwards body bytes exactly as received, so it
// never has to re-encode a message.
#pragma once

#include <cstdint>
#include <string>
#include <string_view>
#include <vector>

namespace hlb {

bool EqualsIgnoreCase(std::string_view a, std::string_view b);

struct Header {
  std::string name;
  std::string value;
};

struct HttpHead {
  // Request line.
  std::string method;
  std::string target;
  // Status line.
  int status = 0;
  std::string reason;
  // "HTTP/1.x": 0 or 1.
  int version_minor = 1;
  std::vector<Header> headers;

  const std::string* Find(std::string_view name) const;
  // Replaces every header called `name` with a single one.
  void Set(std::string_view name, std::string_view value);
  void Add(std::string_view name, std::string_view value) { headers.push_back({std::string(name), std::string(value)}); }
  void Remove(std::string_view name);
  // True if a comma-separated header list (e.g. Connection) contains `token`.
  bool HasToken(std::string_view name, std::string_view token) const;

  std::string SerializeRequest() const;
  std::string SerializeResponse() const;
};

// Removes hop-by-hop headers (RFC 9110 7.6.1) before a message is forwarded,
// including any header the Connection header names. Transfer-Encoding is kept
// because the proxy forwards bodies with their original framing.
void StripHopByHop(HttpHead* head);

const char* ReasonPhrase(int status);

// A complete response generated by the proxy itself (errors, admin API).
std::string MakeResponse(int status, std::string_view body, std::string_view content_type = "text/plain",
                         bool close = false, const std::vector<Header>& extra = {});

enum class BodyKind { kNone, kLength, kChunked, kUntilClose };

class HttpParser {
 public:
  enum class Kind { kRequest, kResponse };
  enum class State { kHead, kBody, kDone, kError };

  explicit HttpParser(Kind kind, size_t max_head_bytes = 64u << 10);

  // Prepares for the next message on the same connection.
  void Reset();
  // Response parsing needs the request method: a response to HEAD has no body.
  void set_request_method(std::string_view method) { request_method_ = std::string(method); }

  // Consumes a prefix of `data` and returns its length. A call consumes
  // either head bytes or body bytes, never both, so callers can tell them
  // apart: keep calling while it makes progress. Never consumes past the end
  // of a message, so any remainder belongs to the next one (pipelining).
  size_t Feed(std::string_view data);
  // The connection hit EOF. Completes read-until-close bodies; anything else
  // is a truncated message.
  void OnEof();

  State state() const { return state_; }
  bool head_complete() const { return state_ == State::kBody || state_ == State::kDone; }
  bool done() const { return state_ == State::kDone; }
  const HttpHead& head() const { return head_; }
  HttpHead& mutable_head() { return head_; }
  BodyKind body_kind() const { return body_kind_; }
  uint64_t content_length() const { return content_length_; }
  bool keep_alive() const;

  // When state() == kError: the status to answer with and a description.
  int error_status() const { return error_status_; }
  const std::string& error() const { return error_; }

 private:
  size_t FeedHead(std::string_view data);
  size_t FeedBody(std::string_view data);
  bool ParseHead(std::string_view text);
  bool DetermineBody();
  void Fail(int status, std::string message);

  enum class ChunkState { kSizeLine, kData, kDataCr, kDataLf, kTrailerLine };

  Kind kind_;
  size_t max_head_bytes_;
  State state_ = State::kHead;
  std::string head_buf_;
  HttpHead head_;
  std::string request_method_;
  BodyKind body_kind_ = BodyKind::kNone;
  uint64_t content_length_ = 0;
  uint64_t remaining_ = 0;
  ChunkState chunk_state_ = ChunkState::kSizeLine;
  std::string line_;
  size_t trailer_bytes_ = 0;
  int error_status_ = 0;
  std::string error_;
};

}  // namespace hlb
